### ISSUE TITLE
Missing GHIElectronics.NETMF.Hardware.dll

### ISSUE THREAD

**Issue by heartlandcoop-prichards** [gralin/nrf24l01#1]
Also not found in GHI Electronics 4.3 SDK directory

**Comment by gralin** [comment]
@heartlandcoop-prichards did you try an older version of the SDK? I think this was written when 4.1 or 4.2 was the latest one.

https://old.ghielectronics.com/support/netmf/sdks

Maybe the renamed it in the new version?
